services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 5s
      retries: 10

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway:/app
      - /app/node-modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - KAFKA_BROKER=kafka:9092
    depends_on:
      restaurants-service:
        condition: service_started
      user-service:
        condition: service_started
      order-service:
        condition: service_started
      kafka:
        condition: service_started

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    volumes:
      - ./order-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mysql:3306/mydb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  restaurants-service:
    build:
      context: ./restaurants-service
      dockerfile: Dockerfile
    volumes:
      - ./restaurants-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mysql:3306/mydb
      - AWS_ACCESS_KEY_ID=AKIA6ODU5YO477EUV3WU
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-northeast-2
      - S3_BUCKET_NAME=testercothi
      - KAFKA_BROKER=kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mysql:3306/mydb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    volumes:
      - ./payment-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@mysql:3306/mydb
      - KAFKA_BROKER=kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  mysql-data:
