services:
  test-db:
    image: mysql:8.0
    container_name: test-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3310:3306"
    volumes:
      - test-data:/var/lib/mysql
    restart: always

volumes:
  test-data:
